version: "3"

services:
  prashant-client-app:
    image: snehalshirture/prashant-digital-client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - prashant-digital
    restart: unless-stopped

  prashant-client-app-api:
    image: snehalshirture/prashant-digital-server
    ports:
      - "5000:5000"
    networks:
      - prashant-digital
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/prashantDB
    restart: unless-stopped

  mongo:
    image: mongo:7.0.16
    ports:
      - "27017:27017"
    networks:
      - prashant-digital
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

networks:
  prashant-digital:
    driver: bridge

volumes:
  mongo-data:
    driver: local

